version: 2.1

parameters:
  test:
    type: string
    default: "Im a test"
  do_release:
    type: enum
    enum: ['no', 'yes '] 
    default: 'no'
  something_s3_something: 
    type: string
    default: 's3yeah'
  testing-hyphen:
    type: string
    default: "hyphen-ated"

jobs: 
  configyml:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "i'm config.yml " # run the `echo` command
      - run: echo << pipeline.parameters.test >> # print the value of the test parameter
      - run: echo << pipeline.parameters.do_release >>
      - run: echo << pipeline.parameters.something_s3_something >>
      - run: echo << pipeline.parameters.testing-hyphen >>
      - run: sleep 1m


workflows:
  configYML: 
    jobs: 
      - configyml
