version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello, World!"

  test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  test-workflow:
      - test

