version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Vitest Tests
          command: npm test
      - run:
          name: "Say Hello"
          command: "echo Hello, World!"
      - run:
          name: "Curl ESPN"
          command: "curl https://www.espn.com"
      - run:
          name: intentionally pass
          command: exit 0

workflows:
  hello-workflow:
    jobs:
      - hello-job
  
