version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "echo Hello, World!"
      - run:
          name: "Curl ESPN"
          command: "curl https://www.espn.com"
      - run:
          name: intentionally fail
          command: exit 1

workflows:
  hello-workflow:
    jobs:
      - hello-job
      -
